AWSTemplateFormatVersion: '2010-09-09'
Description: An AWS Serverless Specification template describing your function.
Resources:
  teleBot:
    Properties:
      CodeUri: s3://telebotlabda/e503a86c19f20fa02eeac2616404d546
      Description: ''
      Events:
        Api1:
          Properties:
            Method: POST
            Path: /telebot
          Type: Api
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Role: arn:aws:iam::853805328779:role/service-role/microservice
      Runtime: python2.7
      Timeout: 3
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
